### ISSUE TITLE
Could you add column-width parametr to function addColumns

### ISSUE THREAD

**Issue by feliksby** [origgami/CMB2-grid#1]
It would be amazing if it works the way like this:
$args = array(
    array($field1, 'span3'),
    array($field2, 'span3'),
    array($field3, 'span6')
)
$row->addColumns($args);

**Comment by pablo-sg-pacheco** [comment]
Humm cool idea. I'll work on that

**Comment by pablo-sg-pacheco** [comment]
It's ready :)

I'm doing like this:

```
$row->addColumns(array(
    array($field1, 'class' => 'col-md-8'),
    array($field2, 'class' => 'col-md-4')
));
```

**Comment by feliksby** [comment]
Awesome! Thanks!

**Comment by pablo-sg-pacheco** [comment]
Glad you liked it
