### ISSUE TITLE
Travis & WordPress coding standards

### ISSUE THREAD

**Issue by jrfnl** [origgami/CMB2-grid#15]
Would you be open to me adding a travis file which will run a PHP lint and do a code style check against the [WP Coding standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/) sniffs ?
This would include some minor changes to make the current code comply with the coding standards.

**Comment by pablo-sg-pacheco** [comment]
I just don't like the wp coding standard about using underscores for naming functions and stuff. I prefer camelcase. But i think we should follow the codex right?

And besides, you are the girl in charge here :)
So yes, no problem.

**Comment by jrfnl** [comment]
> I just don't like the wp coding standard about using underscores for naming functions and stuff. I prefer camelcase.

I get that. In a similar vain, I'm not a fan of yoda conditions.
I know people can feel quite strong about their preferred coding standards, which is why I asked the question ;-)

So what about using WPCS, but excluding the function naming rules ?

> And besides, you are the girl in charge here :)

LOL, and there was me thinking it was your repo ;-)

**Comment by pablo-sg-pacheco** [comment]
LOL

> I get that. In a similar vain, I'm not a fan of yoda conditions.

Don't like yoda conditions too. And to put curly braces on different lines neither.

> So what about using WPCS, but excluding the function naming rules ?

Cool is it possible to do that? I prefer.

I'm realizing i can learn with you and I feel so happy you thought this project is worth spending time. I have to admit I was thinking about putting it aside. So yes it's your repository too :)

**Comment by jrfnl** [comment]
> Cool is it possible to do that? I prefer.

Yup, no problem, I'll just need to figure out which rules to exclude. I'll get this sorted once the three PRs I opened earlier are merged to avoid everything conflicting with different spacing and such.

> I'm realizing i can learn with you and I feel so happy you thought this project is worth spending time. I have to admit I was thinking about putting it aside. So yes it's your repository too :)

Thank you :blush: That's very kind.
I generally will always try to give back to projects I use, so you're very welcome.

**Comment by jrfnl** [comment]
PR #16 addresses this and selectively excludes a few rules. Have a look through if there are other rules you'd want to exclude as well or if you're ok with what I've done now.
