### ISSUE TITLE
How to include it inside another plugin?

### ISSUE THREAD

**Issue by ShariqKhan2012** [origgami/CMB2-grid#26]
This is more of a question than an issue. Is there a way to include this plugin inside another plugin, like we can do with cmb2 itself (by including the init.php) or cmb2-conditionals.

I really like this plugin and it would be great if I could use it in another plugin.

And, thanks for the great work!!

**Comment by pablo-sg-pacheco** [comment]
Thanks!

I think the only way is using composer on your plugin. See if #3 helps you

**Comment by ShariqKhan2012** [comment]
I will have a look at it shortly. Thanks for the quick response :)

**Comment by ShariqKhan2012** [comment]
I keep getting this error:

> Fatal error: Class 'Cmb2Grid\Grid\Cmb2Grid' not found in C:\WAMP\www\wordpress\wp-content\plugins\cmbtest\cmbtest.php on line 213

Line 213 is:
    `$cmb2Grid = new \Cmb2Grid\Grid\Cmb2Grid($cmb_group);`

I have tried it installing cmb2-grid  as a plugin, but still the same error comes up.
I also tried it including explicitly using this line of code in my plugin's file:

```
if ( file_exists( dirname( __FILE__ ) . '/cmb2-grid/Cmb2GridPlugin.php' ) ) {
    require_once dirname( __FILE__ ) . '/cmb2-grid/Cmb2GridPlugin.php';
}
```

I can confirm that Cmb2GridPlugin.php is getting included because I have put debug statements there.

What steps could I be missing?

**Comment by ShariqKhan2012** [comment]
I moved the code from Line 213 (mentioned abpve) to the function attached to the hook, _'cmb2_admin_init'_ and things are fine now.

I was just wondering, is it possible to assign columns to repeatable groups ?

I did something like this:

```
            $prefix      = '_group_columns_test';
            $cmb_group   = new_cmb2_box( array(
                'id'             => $prefix . 'metabox',
                'title'          => __( 'Repeating Field Group using a Grid', 'cmb2' ),
                'object_types'   => array( 'page' ),
            ) );
            // $group_field_id is the field id string, so in this case: $prefix . 'demo'
            $group_field_id  = $cmb_group->add_field( array(
                'id'         => $prefix . 'demo',
                'type'       => 'group',
                'options'    => array(
                    'group_title'    => __( 'Entry {#}', 'cmb2' ), // {#} gets replaced by row number.
                    'add_button'     => __( 'Add Another Entry', 'cmb2' ),
                    'remove_button'  => __( 'Remove Entry', 'cmb2' ),
                    'sortable'       => true,
                ),
            ) );
            $gField1         = $cmb_group->add_group_field( $group_field_id, array(
                'name'   => __( 'Entry Title', 'cmb2' ),
                'id'     => 'title',
                'type'   => 'text',
            ) );
            $gField2         = $cmb_group->add_group_field( $group_field_id, array(
                'name'           => __( 'Description', 'cmb2' ),
                'description'    => __( 'Write a short description for this entry', 'cmb2' ),
                'id'             => 'description',
                'type'           => 'textarea_small',
            ));

            $cmb2Grid = new \Cmb2Grid\Grid\Cmb2Grid( $cmb_group );
            // Create now a Grid of group fields.
            $cmb2GroupGrid   = $cmb2Grid->addCmb2GroupGrid( $group_field_id );

            $row = $cmb2Grid->addRow();
            $row->addColumns( array(
                $cmb2GroupGrid
            ) );
```

This way the group comes up fine, but it takes up full width.

If I change the last line to :

```
            $row->addColumns( array(
                array( $cmb2GroupGrid, 'class' => 'col-md-6' ),
            ) );
```

then it gives me fatal error:

> Fatal error: Cannot use object of type Cmb2Grid\Grid\Group\Cmb2GroupGrid as array

Now if I add another group to make my code look like this:

```
            $prefix      = '_group_columns_test';
            $cmb_group   = new_cmb2_box( array(
                'id'             => $prefix . 'metabox',
                'title'          => __( 'Repeating Field Group using a Grid', 'cmb2' ),
                'object_types'   => array( 'page' ),
            ) );
            // $group_field_id is the field id string, so in this case: $prefix . 'demo'
            $group_field_id  = $cmb_group->add_field( array(
                'id'         => $prefix . 'demo',
                'type'       => 'group',
                'options'    => array(
                    'group_title'    => __( 'Entry {#}', 'cmb2' ), // {#} gets replaced by row number.
                    'add_button'     => __( 'Add Another Entry', 'cmb2' ),
                    'remove_button'  => __( 'Remove Entry', 'cmb2' ),
                    'sortable'       => true,
                ),
            ) );
            $gField1         = $cmb_group->add_group_field( $group_field_id, array(
                'name'   => __( 'Entry Title', 'cmb2' ),
                'id'     => 'title',
                'type'   => 'text',
            ) );
            $gField2         = $cmb_group->add_group_field( $group_field_id, array(
                'name'           => __( 'Description', 'cmb2' ),
                'description'    => __( 'Write a short description for this entry', 'cmb2' ),
                'id'             => 'description',
                'type'           => 'textarea_small',
            ));



            $group_field_id2     = $cmb_group->add_field( array(
                'id'         => $prefix . 'demo2',
                'type'       => 'group',
                'options'    => array(
                    'group_title'    => __( 'DEntry {#}', 'cmb2' ), // {#} gets replaced by row number.
                    'add_button'     => __( 'Add Another DEntry', 'cmb2' ),
                    'remove_button'  => __( 'Remove Entry', 'cmb2' ),
                    'sortable'       => true,
                ),
            ) );
            $gField12        = $cmb_group->add_group_field( $group_field_id2, array(
                'name'   => __( 'DEntry Title', 'cmb2' ),
                'id'     => 'title2',
                'type'   => 'text',
            ) );
            $gField22        = $cmb_group->add_group_field( $group_field_id2, array(
                'name'           => __( 'Description', 'cmb2' ),
                'description'    => __( 'Write a short description for this entry', 'cmb2' ),
                'id'             => 'description2',
                'type'           => 'textarea_small',
            ));


            if ( ! is_admin() ) {
                return;
            }
            // Create a default grid.
            $cmb2Grid = new \Cmb2Grid\Grid\Cmb2Grid( $cmb_group );
            // Create now a Grid of group fields.
            $cmb2GroupGrid   = $cmb2Grid->addCmb2GroupGrid( $group_field_id );      

            $cmb2GroupGrid2  = $cmb2Grid->addCmb2GroupGrid( $group_field_id2 );

            $row = $cmb2Grid->addRow();
            $row->addColumns( array(
                $cmb2GroupGrid, // Can be $group_field_id also.
                $cmb2GroupGrid2
                //array( $cmb2GroupGrid, 'class' => 'col-md-8' ),
                //array( $cmb2GroupGrid2, 'class' => 'col-md-4' )
            ) );
```

then the groups come fine in 2 columns.
However, the problem is that if I click on add button to create one more type of the group. then the new instance comes just below it, it does not come to the next available column.

Perhaps a screenshot would explain better:

![gridcolumns](https://cloud.githubusercontent.com/assets/17094481/16766911/57f45b28-485a-11e6-9c09-6ea743fc8ea8.jpg)

**Comment by devnix** [comment]
I think this commit would patch the issue. https://github.com/origgami/CMB2-grid/pull/24/commits/a330a5e0130e51652e65df8172a3002fe64e9514

**Comment by ShariqKhan2012** [comment]
@DevNix, thanks for the patch. But my original problem related to "_Fatal error: Class 'Cmb2Grid\Grid\Cmb2Grid' not found_" was because I was calling the code from the wrong place.

But I gather that when I use composer, your patch will definitely help, so thanks again for it.

Right now my problem is that when I use grids and assign columns (say col-md-4) to the repeatable group (say $group_field_id), then each new group added by clicking on "Add another entry" does NOT take the column col-md-4. Instead the column col-md-4 remains assigned to the complete $group_field_id as a while; not to each component of it added through the repeater functionality.

Would you have any thoughts for that?

**Comment by devnix** [comment]
Oh, I thougt it was the same error, mine was: 

```
Fatal error: Class 'Cmb2Grid\Grid\Cmb2Grid' not found in /var/www/iteaf/wp-content/plugins/unidad-movil/includes/class-ubicaciones-unidad-movil.php on line 153
```

Mhhh, I still not have any experiences with repeatable groups. @pablo-pacheco will know better, but comes to my mind that CMB2-grid does still not have a good support of repeatable fields? (speaking from my ignorance)

**Comment by ShariqKhan2012** [comment]
The original issue I posted about was because of me placing the code in incoorect place. Nothing wrong with the plugin. Just my code was wrong. 
The second issue is about assigning classes to repeatable groups, which is not related to the original issue I reported. So I think I should close this thread. Perhaps I will start a new one for the columns issue.

**Comment by neotropic2023** [comment]
Well I get "Fatal error: Class 'Cmb2Grid\Grid\Cmb2Grid' not found in" and I have my code in function 'cmb2_admin_init' like the example above. Makes no sense.
