### ISSUE TITLE
composer installer support

### ISSUE THREAD

**Issue by WhereBeTheDan** [origgami/CMB2-grid#28]
Would you consider adding support for [composer/installers](https://github.com/composer/installers)? I'm using this with Trellis and because CMB2-grid doesn't use installers and specify "type": "wordpress-plugin", composer is installing it to the default directory with other dev dependencies.

**Comment by pablo-sg-pacheco** [comment]
You are right. 
I've just made this change. Thanks

**Comment by WhereBeTheDan** [comment]
Awesome, thanks for the quick turn around.
