### ISSUE TITLE
composer.json file

### ISSUE THREAD

**Issue by richardtape** [origgami/CMB2-grid#3]
Would you consider adding (or accepting a PR) which adds a composer.json file for this add-on? I'd like to use it within another plugin I'm building and would like to include it as a dependency (and also autoload the class).

Thoughts?

**Comment by pablo-sg-pacheco** [comment]
You are right. I am so glad you liked it!
I've just commit. I tested and it worked. Take a look

**Comment by pablo-sg-pacheco** [comment]
Just to making things easier, in my test I included it as a dependency creating a composer.json like this:

```
{    
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/origgami/CMB2-grid"
        }
    ],
    "require": {
        "origgami/CMB2-grid": "dev-master"
    }
}
```

**Comment by richardtape** [comment]
:+1:  Great, I'll give this a try today! Thanks for doing this so quickly!
