### ISSUE TITLE
Empty field with settings page

### ISSUE THREAD

**Issue by alfaex** [origgami/CMB2-grid#39]
i'm using the settings page example [settings page](https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php)

and when using the CMBS-Grid the fields return empty, i'm think that ist's bacause i can't set my prefix on the `cmb2_get_option( myprefix_admin()->key, $key, $default );` in the cmb2-grid code i can't find the cmb2_get_option so iyou probably use another method, but looking on the code i don't found a way to make work

PS: sou br, mas como todas as outras perguntas estavam em inglês to perguntando em inglês mesmo, n sei se ficou claro meu problema.

**Comment by pablo-sg-pacheco** [comment]
Hello,

How are you using Cmb2-grid? Can you put your code here?

PS: Sou br tb :) Legal saber

**Comment by alfaex** [comment]
for the test i'm using exactly the example of the link on the first comment

`$telefone = $cmb->add_field( array(
	'name'    => 'Telefone',
	//'desc'    => 'field description (optional)',
	//'default' => 'standard value (optional)',
	'id'      => 'telefone',
	'type'    => 'text',
) );

$telefoneBg = $cmb->add_field( array(
	'name'    => __( 'Test Color Picker', 'myprefix' ),
	//'desc'    => __( 'field description (optional)' ),
	'id'      => 'telefoneBg',
	'type'    => 'colorpicker',
	//'default' => '#bada55',
) );

$cmb2Grid = new \Cmb2Grid\Grid\Cmb2Grid($cmb);
$row = $cmb2Grid->addRow();
$row->addColumns(array($telefone, $telefoneBg));
`

to replicate you can paste the code above in line 142

**Comment by pablo-sg-pacheco** [comment]
Try to use the field id instead, like this:

`$row->addColumns(array('telefone', 'telefoneBg'));`

**Comment by alfaex** [comment]
same thing with `$row->addColumns(array('telefone', 'telefoneBg'));`

**Comment by pablo-sg-pacheco** [comment]
Actually i don't know if cmb2-grid works on a page. I've only tested it as a metabox inside a custom post type. Can you try that? Change this new_cmb2_box() to a default one as a custom post type and tell me if it works

**Comment by alfaex** [comment]
I will try.
Using as a setting page i need to explicity use `cmb2_get_option( 'myprefix', 'id-of-the-field' );` otherwise will not work.

i will try to look if i find a way to modify the code to work with settings page, but it may take a while.

**Comment by alfaex** [comment]
setting up with `'object_types'  => array( 'page')` worked fine.

Thanks anyway, i will try to look under the hood later,maybe i can modify to make it work.

**Comment by pablo-sg-pacheco** [comment]
That's good to know. Thanks
