### ISSUE TITLE
Globally applied box-sizing: border-box is affecting Breadcrumb Nav XT's options page

### ISSUE THREAD

**Issue by daveromsey** [origgami/CMB2-grid#4]
Thank you for making this helpful addon to CMB2!

I've run into a small issue where the options page layout for the [Breadcrumb NavXT](https://wordpress.org/plugins/breadcrumb-navxt/) plugin is affected by CMB2 Grid's CSS which is being loaded globally in the admin

Specifically, it's Bootstrap's global application of box-sizing: border-box. It's messing up the tabs on Breadcrumb NavXT's options pages.

**Comment by pablo-sg-pacheco** [comment]
Thank you for the kind words :)
And thank you for the warning. It should be messing with other plugins too and i wasn't aware.

I think i fixed it. The border-box css property of bootstrap css is being called only on metaboxes now

**Comment by daveromsey** [comment]
Holy smokes that was fast! I've confirmed that the fix worked.

You're a boss, Pablo.
