### ISSUE TITLE
Grid in group fields

### ISSUE THREAD

**Issue by Thoum** [origgami/CMB2-grid#5]
Hi, thank you for this awesome plugin !

I was wondering if it was possible to use it in group fields because i don't manage to do it.
I'm assigning a name to each field of the group, and add it to the column array, but nothing happens (no warning neither).

Thanks in advance for your answer !

**Comment by pablo-sg-pacheco** [comment]
Thanks :)

I've never tried it on group fields. I think it would be harder to manage the html and to design it. But it would be cool.
Can you help me on that? Can you explain me your idea of how it would work?

**Comment by Thoum** [comment]
Thank you for your interest :) , it would help me a lot (cause i'm developing a module with repeatable groups, and a lot of input inside of each, and it'll not be easy to read without grid system) .

I looked at the structure of the groups. It seems to be the same as standard inputs (cmb-rows class) but inside additionnal 'divs'. 

I think the module should detect the use of "add_group_field" 

```
($cmb->add_group_field($group_field))
```

instead of the standard "add_field" 

```
( $field = $cmb->add_field(array(...))
```

OR the "$cmb2Grid" call would be something like 

```
new \Cmb2Grid\Grid\Cmb2Grid($group_field);
```

instead of 

```
new \Cmb2Grid\Grid\Cmb2Grid($cmb);
```

when we want to make grids in groups.

For now, when i do this, worpress show me a message : 

> "﻿Requirements of Metabox needed to obtain a parameter ID". 

I don't know if i'm clear, i tried to explain you as clearly as i can, but the way it works for now is pretty hard to understand for me. Does it helps you? :/

**Comment by pablo-sg-pacheco** [comment]
I've got it.
I have to make some tests and i think it's gonna be harder to implement this.

I'll keep you updated. But don't expect anything soon i'm sorry :(

**Comment by Thoum** [comment]
Don't be sorry, we all have a lot of things to do! 

Thank you for trying :)

**Comment by pablo-sg-pacheco** [comment]
Good news. I think i've made it! :)

Take a look and give it a try
https://github.com/origgami/CMB2-grid/wiki/Group-fields

**Comment by Thoum** [comment]
Hi ! 
Sorry for the (very) late answer, i was in a job rush all week long...
What you made is just awesome ! 
A big thank you ! 
It's just amazing the way it works (as easy as the standard grid system) !

Thank you again for your really good work, it helps me so much for my project! :)  :+1:

**Comment by pablo-sg-pacheco** [comment]
I'm glad you enjoyed it!
Your challenge became a motivation
